<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE sellAuto_list[
	
							
	<!ELEMENT sellAuto_list (ავტომობილი)>
	
	<!ATTLIST sellAuto_list xmlns:a CDATA #REQUIRED	
							xmlns:b CDATA #REQUIRED>

	

	<!ELEMENT ავტომობილი (მწარმოებელი_MERSEDESI,მწარმოებელი_BMW)>
	<!ELEMENT მწარმოებელი_MERSEDESI (a:მოდელი*,b:მოდელი*)>

	<!ELEMENT მწარმოებელი_BMW (b:მოდელი*,a:მოდელი*)>
	
	<!ELEMENT a:მოდელი (კატეგორია,წელი,ძრავა,საწვავი,წამყვანი_თვლები,ფერი,გარბენი,გადაცემათა_კოლოფი,ფასი,კომენტარი)>
	<!ELEMENT b:მოდელი (კატეგორია,წელი,ძრავა,საწვავი,წამყვანი_თვლები,ფერი,გარბენი,გადაცემათა_კოლოფი,ფასი,კომენტარი)>
	<!ATTLIST მოდელი val CDATA #REQUIRED>
	<!ELEMENT კატეგორია (#PCDATA)>
	<!ELEMENT წელი (#PCDATA)>
	<!ELEMENT ძრავა (#PCDATA)>
	<!ELEMENT საწვავი (#PCDATA)>
	<!ELEMENT წამყვანი_თვლები (#PCDATA)>
	<!ELEMENT ფერი (#PCDATA)>
	<!ELEMENT გარბენი (#PCDATA)>
	<!ELEMENT გადაცემათა_კოლოფი (#PCDATA)>
	<!ELEMENT ფასი (#PCDATA)>
	<!ELEMENT კომენტარი (#PCDATA)>
	
	<!ENTITY j "ჯიპი">
	<!ENTITY s "სედანი">

]>

<sellAuto_list
	xmlns:a="FL"
	xmlns:b="NY"
		>
	<ავტომობილი>
	
		
		<მწარმოებელი_MERSEDESI>
			<a:მოდელი val="ML">
				<კატეგორია>&j;</კატეგორია>
				<წელი>2014</წელი>
				<ძრავა>5.0</ძრავა>
				<საწვავი>ბენზინი</საწვავი>
				<წამყვანი_თვლები>4x4</წამყვანი_თვლები>
				<ფერი>შავი</ფერი>
				<გარბენი>123000</გარბენი>
				<გადაცემათა_კოლოფი>ავტომატიკა</გადაცემათა_კოლოფი>
				<ფასი>12500</ფასი>
				<კომენტარი>კარგ მდგომარეობაში</კომენტარი>
	        </a:მოდელი>


			<b:მოდელი val="GL">
				<კატეგორია>&j;</კატეგორია>
				<წელი>2014</წელი>
				<ძრავა>12.0</ძრავა>
				<საწვავი>ბენზინი</საწვავი>
				<წამყვანი_თვლები>4x4</წამყვანი_თვლები>
				<ფერი>შავი</ფერი>
				<გარბენი>155000</გარბენი>
				<გადაცემათა_კოლოფი>მექანიკა</გადაცემათა_კოლოფი>
				<ფასი>56500</ფასი>
				<კომენტარი>მაგარი მანქანაა</კომენტარი>
	        </b:მოდელი>
		</მწარმოებელი_MERSEDESI>
	
		
		
		
		
		<მწარმოებელი_BMW>
			
			<b:მოდელი val="5 series">
				<კატეგორია>&s;</კატეგორია>
				<წელი>2014</წელი>
				<ძრავა>5.0</ძრავა>
				<საწვავი>ბენზინი</საწვავი>
				<წამყვანი_თვლები>4x4</წამყვანი_თვლები>
				<ფერი>შავი</ფერი>
				<გარბენი>123000</გარბენი>
				<გადაცემათა_კოლოფი>ავტომატიკა</გადაცემათა_კოლოფი>
				<ფასი>12500</ფასი>
				<კომენტარი>კარგ მდგომარეობაში</კომენტარი>
	        </b:მოდელი>


			<a:მოდელი val="3 series">
				<კატეგორია>&s;</კატეგორია>
				<წელი>2014</წელი>
				<ძრავა>12.0</ძრავა>
				<საწვავი>ბენზინი</საწვავი>
				<წამყვანი_თვლები>4x4</წამყვანი_თვლები>
				<ფერი>შავი</ფერი>
				<გარბენი>155000</გარბენი>
				<გადაცემათა_კოლოფი>მექანიკა</გადაცემათა_კოლოფი>
				<ფასი>56500</ფასი>
				<კომენტარი>მაგარი მანქანაა</კომენტარი>
	        </a:მოდელი>			
		</მწარმოებელი_BMW>
		
	</ავტომობილი>
</sellAuto_list>