<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE electronics_list[
	
							
	<!ELEMENT electronics_list (laptop)>	
	<!ATTLIST electronics_list xmlns:a CDATA #REQUIRED	
							xmlns:b CDATA #REQUIRED>
	<!ELEMENT laptop (მწარმოებელი_TOSHIBA,მწარმოებელი_MICROSOFT)>
	<!ELEMENT მწარმოებელი_TOSHIBA (a:მოდელი*,b:მოდელი*)>
	<!ELEMENT მწარმოებელი_MICROSOFT (b:მოდელი*,a:მოდელი*)>	
	<!ELEMENT a:მოდელი (ეკრანის_ტიპი,პროცესორი,მეხსიერება,მყარი_დისკი,გრაფიკული_პროცესორი,ფერი,მწარმოებელი_ქვეყანა,ოპერაციული_სისტემა,ფასი,მდგომარეობა)>
	<!ELEMENT b:მოდელი (ეკრანის_ტიპი,პროცესორი,მეხსიერება,მყარი_დისკი,გრაფიკული_პროცესორი,ფერი,მწარმოებელი_ქვეყანა,ოპერაციული_სისტემა,ფასი,მდგომარეობა)>
	<!ATTLIST მოდელი val CDATA #REQUIRED>
	<!ELEMENT ეკრანის_ტიპი (#PCDATA)>
	<!ELEMENT პროცესორი (#PCDATA)>
	<!ELEMENT მეხსიერება (#PCDATA)>
	<!ELEMENT მყარი_დისკი (#PCDATA)>
	<!ELEMENT გრაფიკული_პროცესორი (#PCDATA)>
	<!ELEMENT ფერი (#PCDATA)>
	<!ELEMENT მწარმოებელი_ქვეყანა (#PCDATA)>
	<!ELEMENT ოპერაციული_სისტემა (#PCDATA)>
	<!ELEMENT ფასი (#PCDATA)>
	<!ELEMENT მდგომარეობა (#PCDATA)>	
	<!ENTITY l "LED ">
	<!ENTITY s "სენსორი">
]>

<electronics_list
	xmlns:a="FL"
	xmlns:b="NY"
		>
	<laptop>
	
		
		<მწარმოებელი_TOSHIBA>
			<a:მოდელი val="sattelite C55-C538">
				<ეკრანის_ტიპი>&l;</ეკრანის_ტიპი>
				<პროცესორი>Intel® Core™ i7-5500U Processor</პროცესორი>
				<მეხსიერება>8GB DDR3L 1600MHz</მეხსიერება>
				<მყარი_დისკი>1TB (5400 RPM) Serial ATA hard disk drive</მყარი_დისკი>
				<გრაფიკული_პროცესორი>Mobile Intel® HD Graphics</გრაფიკული_პროცესორი>
				<ფერი>შავი</ფერი>
				<მწარმოებელი_ქვეყანა>ჩინეთი</მწარმოებელი_ქვეყანა>
				<ოპერაციული_სისტემა>Ubuntu 14.04 LTS</ოპერაციული_სისტემა>
				<ფასი>2 450.00 $</ფასი>
				<მდგომარეობა>ახალი</მდგომარეობა>
	        </a:მოდელი>


			<b:მოდელი val="Satellite S55-B5157">
				<ეკრანის_ტიპი>&l;</ეკრანის_ტიპი>
				<პროცესორი>Intel Core i7-5500U </პროცესორი>
				<მეხსიერება>12GB RAM</მეხსიერება>
				<მყარი_დისკი>1TB HDD</მყარი_დისკი>
				<გრაფიკული_პროცესორი>AMD Radeon R7 M260</გრაფიკული_პროცესორი>
				<ფერი>ვერცხლისფერი</ფერი>
				<მწარმოებელი_ქვეყანა>საქართველო</მწარმოებელი_ქვეყანა>
				<ოპერაციული_სისტემა>Windows 8.1 </ოპერაციული_სისტემა>
				<ფასი>349.99 ეროვნული ლარი</ფასი>
				<მდგომარეობა>მეორადი</მდგომარეობა>
	        </b:მოდელი>
		</მწარმოებელი_TOSHIBA>
	
		
		
		
		
		<მწარმოებელი_MICROSOFT>
			
			<b:მოდელი val="Surface Pro 3">
				<ეკრანის_ტიპი>&s;</ეკრანის_ტიპი>
				<პროცესორი>Dual Core 1.9GHz</პროცესორი>
				<მეხსიერება>8GB RAM</მეხსიერება>
				<მყარი_დისკი>320GB</მყარი_დისკი>
				<გრაფიკული_პროცესორი>On-Board Graphics</გრაფიკული_პროცესორი>
				<ფერი>Silver</ფერი>
				<მწარმოებელი_ქვეყანა>USA</მწარმოებელი_ქვეყანა>
				<ოპერაციული_სისტემა>Microsoft Windows 95</ოპერაციული_სისტემა>
				<ფასი>3 450.99 USD</ფასი>
				<მდგომარეობა>ახალი</მდგომარეობა>
	        </b:მოდელი>


			<a:მოდელი val="Surface 3">
				<ეკრანის_ტიპი>&s;</ეკრანის_ტიპი>
				<პროცესორი>1.6GHz</პროცესორი>
				<მეხსიერება>4GB</მეხსიერება>
				<მყარი_დისკი>128GB</მყარი_დისკი>
				<გრაფიკული_პროცესორი>ონბოარდ</გრაფიკული_პროცესორი>
				<ფერი>შავი</ფერი>
				<მწარმოებელი_ქვეყანა>ა.შ.შ</მწარმოებელი_ქვეყანა>
				<ოპერაციული_სისტემა>	Windows, Windows 10</ოპერაციული_სისტემა>
				<ფასი>140$</ფასი>
				<მდგომარეობა>მეორადი</მდგომარეობა>
	        </a:მოდელი>			
		</მწარმოებელი_MICROSOFT>
		
	</laptop>
</electronics_list>